prefix = "pd "
threshold = 35

path = "assets/memory.msgpack"
backup_path = "assets/backup_memories"

webhook_path = "assets/webhooks.json"
templates_path = "assets/templates/"
font_path = "assets/impact.ttf"

#guild_id = 803282468798201927
guild_id = 816054459679113246

blacklist = [
    808887397550653490,
    826831271920664636
]

#approb = "<:SubaApprob:848516371309789265>"
approb = "\U0001F44D"
someone = "@someone"

discord_regex = r"<((@!?\d+)|(:.+?:\d+))>"
default_meme_name = "meme.gif"

commands_and_chat = [
    "delete",
    "saytts"
]

impregnate = """
you indeed got lucky darling but sadly i ran out of cum so i will not be able to impregnate you
dm someone that got the lucky pic of me and they might be able to show it to you
unless you are a minor lol
"""
sex = "okay i understand that you might find me attractive {} but i literally am a piece of Python code hosted on a DigitalOcean hosting service"
grooming = """
why would you even want to do sexual intercourse with {1}, {0}?
probably either you or {1} is underage
i know you would really want to cum on {1}, but please, think about it.
it's better to build a relationship first, at least in my opinion ¯\\\_(ツ)_/¯
"""

erp_channels = (857816615273889813, 857816882899583006) # chill-chat and unholo
reaction_command_fail = "s-sowwy UwU there was too much erp here & thats no good!!!!!!!!!!! so i cant let you do that :3333"

selfhug = "aww, you want a hug? come here!\n"
hug = "come here {}! you got hugged by {}! :D\n"
cocobothug = "you want to hug me? yees please! i love hugs!\n"

selfkiss = "you want a kiss? i mean sure! <3\n"
kiss = "heyo, come here {}! you got kissed by {}!\n"
cocobotkiss = "y-you want to k-kiss me? only once!! okay?\n"

selfpat = "even though i don't have a hand, i will pat you! :)\n"
pat = "get your hand down there {}! you got a pat by {}!\n"
cocobotpat = "yaay! cocobot pat :D\n"

selfslap = "i mean if you want it then get slapped by me!\n"
slap = "be careful {}! you got slapped by {}!\n"
cocobotslap = "ouch, that hurts, don't do that again\n"

crimid = 720795980517081108
crimhug = "awwwwwww, my creator's cutie pie wants a hug? that's soooo sweet <3333\n"
crimkiss = "i will always reserve a kiss for my mommy's sweetie!\n"
crimpat = "where's your head crim? i need it to give it as much love in form of a pat!!\n"

temperature_file = "/sys/class/thermal/thermal_zone0/temp"

doxx = """
{} IP Address: {}
anyways {} answer the doorbell NOW <:0Rapist:885280968452227122>
"""
cocodoxx = """
you really think i am THAT stupid to just doxx myself like that?
if yes, then you were wrong ¯\\\_(ツ)_/¯
"""

credits = """
```
Thank you so much, brook, for funding hosting on DigitalOcean!
Thanks Noswa for drawing her avatar, basically making her body!
Also thank you, denki & eggdog, for making your chatbots first, being an inspiration for cocobot!

Thank you, CringeCrimson, for being a betatester from the very beginning!
I also gotta feature Tadokoro Kouji, for helping gather clips for 'pd clips', 
and artemis_, with gathering stuff for 'pd insult'! 

Thank you real gawr gura (real!!!) and bruhallah with 'pd ratio', collecting messages and images for it!
Github Copilot is also a big help, for helping me with the code!
 
and, of course, thank you Holotards, for using the bot and having fun with her <3
- bemxio
```
"""

kickmsg = "bye retard {}  # **{}** https://tenor.com/view/watame-ripbozo-packwatch-restinpiss-gif-21991440"
graduation = [
    "she was so cute...",
    "i loved her so much...",
    "i still can't get over it...",
    "i wished she stayed with us...",
    "where will i get my asacoco dose from now...",
    ":')"
]
rape = """
yeah pal, you should think about it
you already know that it's illegal even when you are not raping an underaged person, right?
oh yeah also fun fact: castration is sometimes a punishment for rape and, controversially, 
some U.S. jurisdictions allow shorter sentences for sex criminals who agree to voluntary chemical castration
so that's funny

anyways don't do it lol 
"""

billing = """
current account balance: **${}**
time left: **~{}** hours (~{} days)

paying $0.007/h (~$0.17/d) on vacations in the digital ocean :)
"""

gold = """
Sorry, this post requires an {} GOLD subscription to view.

To purchase an {} GOLD subscription, please reply with your social credit score and physical address.
"""

helpdocs = {
    "help": {
        "usage": "pd help",
        "description": "displays this help messsage\n"
    },
    "impersonate": {
        "usage": "pd impersonate <@user> <message>",
        "description": """
        impersonates a user invoking the command or the user specified in `<@user>`,
        with sending a message either generated by cocobot, or the one specified in `<message>`.
        """
    },
    "@cocobot": {
        "usage": "<@cocobot> <text>",
        "description": """
        replies to a user invoking the command with a generated response, based on `<text>` (if present).
        """
    },
    "@cocobot voice": {
        "usage": "<@cocobot> voice",
        "description": """
        same as @cocobot, except that it will say the message via TTS into a voice channel, 
        if the user invoking the command is currently in a voice channel.
        """
    },
    "saytts": {
        "usage": "pd saytts <message>",
        "description": """
        says a message specified in `<message>` via TTS into a voice channel, 
        if the user invoking the command is currently in a voice channel.
        """
    },
    "@someone": {
        "usage": "@someone",
        "description": """
        will ping (mention) a random member in the guild the command is invoked.
        """
    },
    "impregnate": {
        "usage": "pd impregnate",
        "description": """
        i dunno, try it yourself! you have a 1% chance of it doing something though :^)
        """
    },
    "sex": {
        "usage": "pd sex <@user>",
        "description": """
        kindly informs you about the dangers of commiting sexual intercourse with random people on the internet.
        """
    },
    "hug": {
        "usage": "pd hug <@user>",
        "description": """
        hugs you (or `<@user>`) to cheer up both of you :))
        """
    },
    "kiss": {
        "usage": "pd kiss <@user>",
        "description": """
        kisses you (or `<@user>`) if you really like it~
        """
    },
    "pat": {
        "usage": "pd pat <@user>",
        "description": """
        pats you (or `<@user>`) for fun :D
        """
    },
    "slap": {
        "usage": "pd slap <@user>",
        "description": """
        makes your (or `<@user>`) face hurt a bit
        """
    },
    "doxx": {
        "usage": "pd doxx <@user>",
        "description": """
        hacks into the mainframe and gets your (or `<@user>`) IP address, in which it secretly harvests your location.
        """
    },
    "fakekick / leave": {
        "usage": "pd [fakekick|leave] <@user>",
        "description": """
        impersonates Saiki Koronbot by sending a "bye retard `<@user>` message (okbuddyhololive only)
        """
    },
    "insult": {
        "usage": "pd insult <@user>",
        "description": """
        insults you (or `<@user>`) to feed one's masochistic tendencies
        """
    },
    "compliment": {
        "usage": "pd compliment <@user>",
        "description": """
        compliments you (or `<@user>`) so that they can be more happy
        """
    },
    "gold": {
        "usage": "pd gold <@user>",
        "description": """
        tells you what do you need to have to be able to view a post (or `<@user>`'s post)
        """
    },
    "ratio": {
        "usage": "pd ratio",
        "description": """
        ratios you 
        """
    },
    "credits": {
        "usage": "pd credits",
        "description": """
        credits all people that made cocobot.
        """
    }
}

# error messages
missingperms = """
admins didnt give me enough perms to do that lol
if youre the admin i need manage messages, manage channels and manage webhooks perms to work properly :)
"""
userinputerror = """
you didnt type the command correctly lmaoooo if you dont know how to do it check out pd help
"""
unexpected = """
uh oh, i did a big oopsie and dunno what to do
please dm bem about it and send him that the cause of it was this thing below
```
{}
```
"""